# create a tag on version change
# version changes are detected by the version in the setup.py file
# the tag is created with the version number and the commit message example: v1.0.0 - initial commit
# the tag is pushed to the repository

name: Create Tag on Version Change

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Get Version
        id: get_version
        run: |
          echo "::set-output name=version::$(python get_version.py)"

      - name: Create Tag
        if: steps.get_version.outputs.version != ''
        run: |
          git tag -a v${{ steps.get_version.outputs.version }} -m "v${{ steps.get_version.outputs.version }} - initial commit"
          git push origin v${{ steps.get_version.outputs.version }}

