# create a tag on version change
# version changes are detected by the version in the setup.py file
# the tag is created with the version number and the commit message example: v1.0.0 - initial commit
# the tag is pushed to the repository

name: Create Tag on Version Change

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # set user name and email
      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Tag
        id: create_tag
        run: |
          python create_tag.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Tag
        if: steps.create_tag.outputs.tag_created == 'true'
        run: |
          git push origin ${{ steps.create_tag.outputs.tag }}

