name: Create Tag on Version Change

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get Package Version
        id: package-version
        run: |
          version=$(grep "version=" setup.py | sed "s/version=['\"]\([^'\"]*\)['\"]/\1/")
          echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV
          echo "::set-output name=version::$version"

      - name: Create Git Tag
        run: |
          git tag ${{ steps.package-version.outputs.version }}
          git push origin ${{ steps.package-version.outputs.version }}
